
CREATE TABLE IF NOT EXISTS `APPLIANCE_TRANS` (
  `ID` BIGINT(20) NOT NULL,
  `SERIAL_NUMBER` VARCHAR(100) NOT NULL DEFAULT 'SN_99999_0120',
  `USER_ID` BIGINT(20) NOT NULL,
  `PRODUCT_NAME` VARCHAR(100) DEFAULT NULL,
  `PRODUCT_DESC` VARCHAR(300) DEFAULT NULL,
  `IMAGE_ID` BIGINT(20) DEFAULT 0,
  `BRAND` VARCHAR(100) DEFAULT NULL,
  `MODEL` VARCHAR(100) DEFAULT NULL,
  `STATUS` VARCHAR(100) DEFAULT NULL,
  `DATE_BOUGHT` DATETIME DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `UPDATE_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `APPLIANCE_TRANS_PK` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;


CREATE TABLE IF NOT EXISTS `USER_TRANS` (
  `ID` BIGINT(20) NOT NULL,
  `FULLNAME` VARCHAR(100) DEFAULT NULL,
  `EMAIL` VARCHAR(100) DEFAULT NULL,
  `USERNAME` VARCHAR(100) DEFAULT NULL,
  `PASSWORD` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_TRANS_PK` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;